#### Learn to Compute with Big Data  

...............

### Data and Computing Fundamentals

...............

#### A new 1-credit course: Spring 2013: Profs. Kaplan and Shoop

### No Pre-Requisites!

The *Data and Computing Fundamentals* course is being developed by Profs. Kaplan and Shoop here at Macalester.  It's part of Macalester's HHMI project to improve science education and prepare students for the data-intensive science of the 21st century.  

In Spring 2013, the course will be offered in prototype form to a group of approximately 20 students.  Eventually it will be a co-requisite for courses such as Applied Calculus, Statistical Modeling, General Chemistry, and Genetics; over the next several years it will be ramped up to an expected enrollment of about 200 students per year. 

This is your chance to get in on the ground floor --- a small class team-taught by two professors.  By doing so, not only will you be learning about Big Data and gaining useful skills, you'll be helping to shape the curriculum for students in future years.  Join us!  There are no pre-requisites!

As a one-credit course, most students will be able to add the course to their existing schedule without any re-adjustment.  The one-credit course will meet for 10 hours spread over 8 weeks, about 1/4 of the classroom time of a 4-credit course. It will involve about one-quarter the amount of work of a regular course.

Our plan is to meet on Tuesdays (time to be arranged based on the schedules of those interested in participating).  

* **Feb 12**: Introduction, data files, documentation markup and elementary graphical visualization
* **Feb 17**: Relational database operations, intermediate visualization
* **Feb 26**: More data operations, map visualization
* **Mar 5**:  Basic models, fitting, and summaries
* **Mar 12**: Clustering
* **Mar 26**: Dimension reduction
* **Apr 2**: Putting it all together



We'll sign students up during Add/Drop period.  

For now, you can get on the mailing list for future announcements.
<a href="mailto:kaplan@macalester.edu?subject=Data%20and%20Computing%20Fundamentals:%20Mailing%20List">Get on the mailing list!</a>


