GGPLOT2 explorations
========================================================

```r include=FALSE
require(mosic)
require(ggplot2)
```

* A blog posting on an attempt to use [manipulate and ggplot2](http://www.r-bloggers.com/a-first-go-at-%E2%80%98manipulate%E2%80%99-in-rstudio/)
* A [ggplot2 tutorial](https://wiki.nbic.nl/index.php/R_ggplot2_tutorial)

### My Shot at it.


Assembling a `ggplot` call given some variable names:
```{r}
scatterString <- function(s){
  res <- paste("ggplot(data=",s$dat,")",sep="")
    res<-paste(res,"+geom_point(aes(x=",s$x,",y=",s$y,"))",sep="")
  if (!is.na(s$color))
    res<-paste(res, "+aes(colour=",s$color,")",sep="")
  if (!is.na(s$size))
    res<-paste(res,"+aes(size=",s$size,")",sep="")
  if (s$logx)
    res <- paste(res,"+scale_x_log10()",sep="")
  if (s$logy)
    res <- paste(res,"+scale_y_log10()",sep="")
  cat(res)
  if (!is.na(s$facet))
    # res<-paste(res,"+facet_wrap(",facet,")",sep="")
  cat(res)
  return(res)
}

barString <- function(s){
  fillStr <- if( is.na(s$fill) ) ")" else paste(",fill=",s$fill,")",sep="")
  aesStr <- paste("aes(x=",s$x,",y=",s$y, fillStr,sep="")
  res <- paste("ggplot(data=",s$dat,",",aesStr,")",sep="")
  res<-paste(res,"+geom_bar(stat='identity')", sep="")
  return(res)
}

doBar <- function(show=FALSE,dname,x=NA,y=NA,color=NA,fill=NA,facet=NA){
  vals <- list(dat=dname,x=x,y=y,color=color,fill=fill,facet=facet)
  s <- barString(vals)
  if (show) cat(paste(s,"\n"))
  p <- eval(parse(text=s))
  print(p)
  return(p)
}
mBar <- function(dat) {
  df = substitute(dat)
  nm = names(dat)
  vnames <- v2list(nm)
  cnames <- snames <- c(list(none=NA),vnames)
  manipulate({p<-doBar(show,df,x=x,y=y,color=color,fill=fill)},
             show = button("Show Expression"),
             x = picker(vnames,initial=nm[1],label="x axis"),
             y = picker(vnames,initial=nm[2],label="y axis"),
             fill = picker(cnames, initial="none",label="Bar fill"),
             color = picker(cnames, initial="none",label="Color")
             )
}

```

Converting a vector of names into a list.
```{r}
v2list <- function(nms) {
  res = list()
  res[nms] <- nms
  return(res)
}
```

Testing a manipulate command:
```{r}
dogg <- function(show=FALSE,dname,x=NA,y=NA,color=NA,size=NA,facet=NA,logx=FALSE,logy=FALSE){
  vals <- list(dat=dname,x=x,y=y,color=color,size=size,facet=facet,logx=logx,logy=logy)
  s <- scatterString(vals)
  if (show) cat(paste(s,"\n"))
  p <- eval(parse(text=s))
  print(p)
  return(p)
}

mgg <- function(dat) {
  df = substitute(dat)
  nm = names(dat)
  vnames <- v2list(nm)
  cnames <- snames <- c(list(none=NA),vnames)
  manipulate({p<-dogg(show,df,x=x,y=y,color=color,size=size,facet=facet,logx=logx,logy=logy)},
             show = button("Show Expression"),
             x = picker(vnames,initial=nm[1],label="x axis"),
             y = picker(vnames,initial=nm[2],label="y axis"),
             color = picker(cnames, initial="none",label="Color"),
             size = picker(snames, initial="none",label="Size"),
             facet = picker(snames, initial="none", label="Facet"),
             logx = checkbox(label="Log X-axis"),
             logy = checkbox(label="Log Y-axis")
             )
}
```

Maybe call this `mScatter`