Creating Bar Plots
======================

```{r include=FALSE}
require(DCF)
options(na.rm=TRUE)
```

You can generate a bar plot from a data frame with the interactive `mBar()` command.

Each individual case in the data frame will become a bar or part of a bar.

Bar plots are effective when there are a handful of groups to perhaps 50 to 100.  Ultimately, it's a matter of taste, but if you are making a bar for each of 2000 cases, it's unlikely that the bar-plot format is what you really want.

Usually, you will be making a bar plot from a data frame generated by a grouping operation, such as `groupBy()`.  

### Choices to make

* What should be the variable on the horizontal axis, and what on the vertical axis.
    * Commonly, the horizontal axis shows a grouping variable, the vertical axis a quantitative variable such as a count.
    * We'll call the grouping variable on the horizontal axis the "main group".
* The order of the bars on the horizontal axis.  
    * The default is alphabetical, but this is not necessarily a good choice unless your purpose is to let the viewer look up values for a particular group.
* Are there subgroups?  
    * Subgroups involve a second grouping variable.  Given that you have two grouping variables --- one for the horizontal axis and one for the subgroups --- you should be thoughtful about which variable should be which.  
* The order for the subgroups.
    * The same comment applies as for the order of the bars on the horizontal axis.
* The style of subgroup display. There are three possibilities:
    * Stacked. Is you want to compare subgroups between main groups, use this.
    * Side-by-side.  If you want to compare subgroups within the main group, this is best.
    * Stacked and proportional.  It only makes sense to do this when the vertical axis is a count, which can sensibly be converted to a proportion of all the cases in the group.