

```{r}
require(DCF)
startTemplate()
```

### A brush-able, interactive parallel coordinates plot: [here](http://syntagmatic.github.com/parallel-coordinates/)


An example of a parallel plot: characteristics of cars:
```{r}
parallelPlot(mtcars, ~ wt +  cyl + disp + hp - mpg,lwd=5,axes=TRUE,alpha=.5)
```
Which car is the sports-car?

Which are the econo-boxes?

What exceptions are there to the rule: lighter weight means better gas mileage?

