Introduction: Data and Computing Fundamentals
==============

### Goals for the Course

This course is intended to give you basic skills in data handling and visualization.  Such skills are more important than ever before.  The reason for this is simple: there is more data available than ever before. 

There are three main steps in working with existing data:
1. **Accessing data**.  This is often simple, particularly now that so much data is published via the Internet.
2. **Reshaping the data**.  This can mean several things: calculating useful summaries of data, combining related data from different sources, reformating data to work with the tools at hand or to be able to affect the combination with other data.
3. **Presenting the data** so that it can be made us of by a human decision maker.

With the right tools, each of these steps can be accomplished easily with modern computers.  In this course, we'll introduce you to some of those tools.  More important, you'll gain an understanding of central concepts in the organization and presentation of data.  With those concepts, you'll be able to approach a new data problem and develop a strategy for handling it.

It's said that to become an expert requires about 10,000 hours of experience. (Source: Malcolm Waldrup???)  That corresponds to working full time for about five years.  In terms of data expertise, that's about right.  There are many different tools, languages, formats, and displays.  There are technical details that complicate combining data from different sources, akin to the "details" of translating from one language to another.

This course is intended to be completed in about 25 hours.  That will put you only a tiny fraction --- 1/400 --- of the way down the road to becoming an expert.  We believe, however, that it's enough time to give you a broad picture of working with data and to give you control of important and powerful tools and concepts. You'll be able to construct data presentations of considerable sophistication.  Although you won't be an expert or know about every aspect of working with data, you will become familiar with many of the most powerful strategies.  Like a new driver, you'll be able to navigate and get around town and will, we hope, develop enough skill to be able to improve further on your own. 

### Learning to Write for the Computer 

You know how to take notes and write a report.  You're used to various tools for this: pens and notebooks, computers and word processors.  

Now you have to learn a new skill: how to write for the computer.  Direct the computer, document your work so that you can correct, refine, and improve it.  
You're familiar with 

Documentation and reproducibility.  
How to create 

### What's Data

