### Data and Computing Fundamentals

Exercises on R Syntax
============

```{r include=FALSE}
require(DCF)  # boilerplate: leave this alone
options(rm.na=TRUE)
```

### Your Name Here

##### `r I(date())`

------



Answer the following by constructing appropriate R commands and/or giving a text narrative.

#### Object Names

Show that names with different capitalization refer to different objects.

Try to create several objects with different types of illegal names.  

#### Strings and Names

Show that a string and a name are different.

Assign a string value to an object.

#### Numbers and Arithmetic

Use scientific notation to create these numbers: 100, 10, 0.001, 0.0000001

Try these mathematical operations and explain what the values mean:
* 1/0
* 0/0
* sqrt(-3)

What's the difference between `NaN` and `NA`?

#### Functions and arguments 

Show that the order of unnamed arguments makes a difference.  Use `seq()` to illustrate this.

Find the names of the arguments to `seq()`.  Show that when you use the names, the order doesn't matter.

What kind of object is created by `date()`?

#### Data Frames

Read in the data set "utilities.csv" with `fetchData("utilities.csv")`

How many rows are there?

What are the names of the variables?

#### R Markdown Syntax

Write the Markdown to reproduce this outline

### Fruits

1. Sweet
    * Apples
    * Pears
    * Grapes
2. Sour
    * Lemons
3. Savory
    * Tomatoes

### Vegetables

1. Leafy
    * Lettuce
    * Kale
    * Cabbage
2. Flower
    * Broccoli
    * Asparagus
    

