Tools/Resources to Consider
========================================================

As we find new things, let's list them here so that we have a record.

### Data

* Gapminder: <http://www.gapminder.org/data>
* Environmental, country-by-country: <http://epi.yale.edu/downloads>

### Books/Courses

* [Coursera.com data science course](https://www.coursera.org/course/datasci) requires python or JAVA.

### People/Contacts

* [Seth Madison](seth.madison@gmail.com) who works at Compete, Inc. in Boston.


### News Articles

* [Match making](http://www.nytimes.com/2013/02/12/science/skepticism-as-eharmony-defends-its-matchmaking-algorithm.html?_r=0)
* [Making personal connections](http://dealbook.nytimes.com/2013/02/11/a-database-of-names-and-how-they-connect/)
* [Data and social welfare in India](http://www.nytimes.com/2013/02/13/opinion/friedman-when-et-and-it-meet-id.html?_r=0)
* [Personal health-related data](http://gadgetwise.blogs.nytimes.com/2013/02/12/a-patch-that-monitors-the-body/)
* [Insurance and big data](http://www.analyticbridge.com/profiles/blogs/excerpt-from-too-big-to-ignore)
* [Identifying Persuadable Voters](http://www.thefiscaltimes.com/Articles/2013/01/21/The-Real-Story-Behind-Obamas-Election-Victory.aspx#page1)
* [Watch your driving](http://www.teslamotors.com/blog/most-peculiar-test-drive) with the [original article](http://www.nytimes.com/2013/02/10/automobiles/stalled-on-the-ev-highway.html) and an [ombudsman's review](http://publiceditor.blogs.nytimes.com/2013/02/18/problems-with-precision-and-judgment-but-not-integrity-in-tesla-test/?hp)

### Graphics commentary

* [Bad graphics](http://www.biostat.wisc.edu/~kbroman/topten_worstgraphs/)

### Unexamined

* [Hadoop and R](http://www.linkedin.com/groups/Using-R-Hadoop-webinar-January-77616.S.202738754?view=&gid=77616&type=member&item=202738754&trk=eml-anet_dig-b_nd-pst_ttle-cn&_mSplash=1)
* [Database instructional materials](http://www.dataone.org/education-modules)
* [64 interview questions for data scientists](http://www.datasciencecentral.com/profiles/blogs/66-job-interview-questions-for-data-scientists?goback=%2Egde_77616_member_213965264)

### In progress

* ggplot2 --- Danny is writing a simple R-GUI for this, so that students can construct plots easily and get the command out.  DTK wrote `mScatter()` and `mBar()`
* rworldmap --- for making easy world maps.

### Discarded

Put the things we've decided not to use here.
